image: node:15.12.0-buster

stages:
  - test
  - bump_version
  - release
  - release_deploy
  - release_notify

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  TRELLIS_GIT_POST: https://trellis.getto.systems/git/post/1.5.2
  TRELLIS_CI_BUMP_VERSION: https://trellis.getto.systems/ci/bump-version/1.12.0
  TRELLIS_PSYCHER_GETTO: https://trellis.getto.systems/psycher/getto/2.7.2

test:
  stage: test
  only:
    refs:
      - merge_requests
    changes:
      - lib/**/*.ts

  variables:
    SECURE_SERVER_URL: https://secure.example.com
    API_SERVER_URL: https://api.example.com

  before_script:
    - npm clean-install
  script:
    - npm test
    - npm run build

bump_version:
  stage: bump_version
  only:
    refs:
      - triggers
    variables:
      - $RELEASE

  image: buildpack-deps:buster-scm

  before_script:
    - git config user.email admin@getto.systems
    - git config user.name getto
    - curl $TRELLIS_GIT_POST/setup.sh | sh -s -- ./vendor/getto-systems
    - export PATH=$PATH:./vendor/getto-systems/git-post/bin
  script:
    - curl $TRELLIS_CI_BUMP_VERSION/bump_version.sh | bash
    - curl $TRELLIS_CI_BUMP_VERSION/request.sh | bash -s -- ./.ci/message/bump.sh

release:
  stage: release
  only:
    refs:
      - release@getto-systems-base/projects/example/ui
    changes:
      - .release-version
  except:
    refs:
      - triggers
      - schedules

  image: buildpack-deps:buster-scm

  script:
    - curl $TRELLIS_CI_BUMP_VERSION/push_tags.sh | sh

release_deploy:
  stage: release_deploy
  only:
    refs:
      - release@getto-systems-base/projects/example/ui
    changes:
      - .release-version
  except:
    refs:
      - triggers
      - schedules
  when: on_success

  variables:
    BUILD_ENV: production
  before_script:
    - apt-get update && apt-get install -y python3-pip
    - pip3 install awscli
    - npm clean-install
  script:
    - ./.ci/deploy.sh

release_success:
  stage: release_notify
  only:
    refs:
      - release@getto-systems-base/projects/example/ui
    changes:
      - .release-version
  except:
    refs:
      - triggers
      - schedules
  when: on_success

  image: buildpack-deps:buster-curl

  before_script:
    - export url=$GETTO_PSYCHER_URL?$GETTO_PSYCHER_TOKEN=true
    - export channel=$SLACK_CHANNEL
    - export version=ui:$(cat .release-version)
  script:
    - curl $TRELLIS_PSYCHER_GETTO/notify-release-success.sh | sh -s -- $url $channel $version

release_failure:
  stage: release_notify
  only:
    refs:
      - release@getto-systems-base/projects/example/ui
    changes:
      - .release-version
  except:
    refs:
      - triggers
      - schedules
  when: on_failure

  image: buildpack-deps:buster-curl

  before_script:
    - export url=$GETTO_PSYCHER_URL?$GETTO_PSYCHER_TOKEN=true
    - export channel=$SLACK_CHANNEL
    - export version=ui:$(cat .release-version)
  script:
    - curl $TRELLIS_PSYCHER_GETTO/notify-release-failure.sh | sh -s -- $url $channel $version
